home/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.home, name="home"),
]

jonathanjocan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    
]

story8/urls.py
from django.urls import path
from . import views

app_name = "story8"

urlpatterns = [
    path('', views.story8Home, name="home"),
]

story9/urls.py
from django.urls import path
from . import views

app_name = "story9"

urlpatterns = [
    path('', views.account, name="home"),
    path('login', views.log_in, name="login"),
    path('logout', views.log_out, name='logout')
]

home/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

story8/views.py
from django.shortcuts import render
import requests
from django.http import JsonResponse

# Create your views here.
def story8Home(request) :
    return render(request, 'story8.html')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def account(req):
    error = "Your username or password is incorrect."
    user = req.user
    if user.is_authenticated:
        return redirect('story9:login')
    if req.method == 'POST':
        form = AuthenticationForm(data=req.POST)
        if form.is_valid():
            user = form.get_user()
            login(req, user)
            return redirect('story9:login')
    else:
        form = AuthenticationForm()
    return render(req, 'account.html', {'form':form, 'error':error})

def log_in(req):
    return render(req, 'login.html')

def log_out(req):
    logout(req)
    return redirect('story9:home')

home/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" data-theme='light'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block css %}{% endblock css %}
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,700|Raleway:400,700&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/4b60c8a34d.js"></script>
    <title>Jocan Story {% block judul %}{% endblock judul %} Cuy</title>
</head>
<body>
    <div class= "judul">
        <h1>Jocan</h1>
        <a href="{% url 'story7:home' %}">Story 7</a>
        <a href="{% url 'story8:home' %}">Story 8</a>
        <a href="{% url 'story9:home' %}">Story 9</a>
        {% block content %}
        {% endblock %}
</body>
</html>

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'home.css' %}">{% endblock css %}
{% block judul %}7{% endblock judul %}
{% block content %}
        <div class='toggle-btn'>
            <div class="inner-circle">
                <i class="fas round"></i>
            </div>
        </div>
    </div>
    <div class="heading">
        <h1>Halo lagi di web Jocan</h1>
    </div>
    <div class="isi">
        <div class='accordion'>
            <div class="container-accord">
                <div class="kotak" name='aktivitas'>
                    <h1>Aktivitas Jocan</h1>
                    <i class="fas fa-caret-down"></i>
                </div>
                <div class="paragraph" name="isi-aktivitas">
                    <ul>
                        <li>Nugas</li>
                        <li>Panit</li>
                        <li>Nugas lagi ada TP3 aaaa</li>
                        <li>Panit lagi</li>
                        <li>Kapan bobonya :(</li>
                    </ul>
                </div>
            </div>
            <div class="container-accord">
                <div class="kotak" name='pengalaman'>
                    <h1>Pengalaman Kepanitiaan/Organisasi</h1>
                    <i class="fas fa-caret-down"></i>    
                </div>
                <div class="paragraph" name="isi-pengalaman">
                    <ul>
                        <li>Staf Biro Media BEM Fasilkom UI 2019</li>
                        <li>Staf Playground COMPFEST XI</li>
                        <li>Staf Bazkom CGT 2019</li>
                        <li>Staf Natal KMK UI 2018</li>
                        <li>Staf Badminton OLIM 2018</li>
                    </ul>    
                </div>
            </div>
            <div class="container-accord">
                <div class="kotak" name='prestasi'>
                    <h1>Prestasi Jocan</h1>
                    <i class="fas fa-caret-down"></i>   
                </div>
                <div class="paragraph" name="isi-prestasi">
                    <ul>
                        <li>Membuat orang lain tertawa dan tersenyum :)</li>
                        <li>Tidur nyenyak pas lagi gempa</li>
                        <li>Makan banyak tapi ga gendut-gendut</li>
                        <li>Abis begadang tapi ga ngantuk seharian (Awakened my eyes)</li>
                        <li>Sekian :), doakan Jocan ya gaes biar dapet prestasi yang lebih berguna dari ini semua</li>
                    </ul>  
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'home.js' %}"></script>
{% endblock %}

jonathanjocan/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" data-theme='light'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,700|Raleway:400,700&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'home.js' %}"></script>
    <script src="https://kit.fontawesome.com/4b60c8a34d.js"></script>
    <title>Jocan Story 7 & 8 Cuy</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

story8/templates/story8.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'story8.css' %}">{% endblock css %}
{% block judul %}8{% endblock judul %}
{% block content %}
</div>
    <h1>Halo lagi di web Jocan</h1>
    <div class='search'>
        <input type="text" placeholder="Search Title" id='search'>
        <div id="button"><i class="fas fa-search"></i></div>
    </div>
    <div id='result'>
        <table id='rslt-table'>

        </table>
    </div>
    <script src="{% static 'story8.js' %}"></script>
{% endblock %}

story9/templates/account.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'story9.css' %}">{% endblock css %}
{% block judul %}9{% endblock judul %}
{% block content %}
</div>
    <h1>Halo lagi di web Jocan</h1>
    <h2>Log in KUY</h2>
    {% if form.errors %}
    {{error}}
    {% endif %}
    <form method="POST" action='{% url "story9:home" %}'>
        {% csrf_token %}
        <label>Username</label>
        <br>
        {{ form.username }}
        <br>
        <label>Password</label>
        <br>
        {{ form.password }}
        <br>
        <input type="submit" value="Log in" class="button">
    </form>
{% endblock %}

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'story9.css' %}">{% endblock css %}
{% block judul %}9{% endblock judul %}
{% block content %}
</div>
    {% if user.is_authenticated %}
    <h1>Halo apa kabar {{user}}</h1> 
    <a href="{% url 'story9:logout' %}">
        <div class='logout'>
            Log out
        </div>
    </a>
    {% else %}
    <h1>You are not logged in.</h1>
    <a href="{% url 'story9:home' %}">
        <div class='login'>
            Log in
        </div>
    </a>
    {% endif %}

{% endblock %}